export const COLOR_CATEGORIES = {
  'General Knowledge': 'bg-yellow-400',
  Books: 'bg-purple-400',
  Film: 'bg-red-500',
  Music: 'bg-pink-500',
  'Musicals & Theatres': 'bg-red-600',
  Television: 'bg-blue-500',
  'Video Games': 'bg-green-500',
  'Board Games': 'bg-blue-400',
  'Science & Nature': 'bg-teal-400',
  Computers: 'bg-indigo-500',
  Mathematics: 'bg-yellow-500',
  Mythology: 'bg-orange-400',
  Sports: 'bg-green-600',
  Geography: 'bg-teal-500',
  History: 'bg-gray-500',
  Politics: 'bg-blue-600',
  Art: 'bg-pink-400',
  Celebrities: 'bg-purple-500',
  Animals: 'bg-green-400',
  Vehicles: 'bg-gray-400',
  Comics: 'bg-yellow-600',
  Gadgets: 'bg-indigo-400',
  'Japanese Anime & Manga': 'bg-red-400',
  'Cartoon & Animations': 'bg-blue-300'
}
